//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.Modules.Presets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresetsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresetsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.Modules.Presets.Resources.PresetsResource", typeof(PresetsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string PresetProperty_Actor {
            get {
                return ResourceManager.GetString("PresetProperty_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AspectRatio.
        /// </summary>
        public static string PresetProperty_AspectRatio {
            get {
                return ResourceManager.GetString("PresetProperty_AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioFormat.
        /// </summary>
        public static string PresetProperty_AudioFormat {
            get {
                return ResourceManager.GetString("PresetProperty_AudioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PresetProperty_Author {
            get {
                return ResourceManager.GetString("PresetProperty_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string PresetProperty_Bitrate {
            get {
                return ResourceManager.GetString("PresetProperty_Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string PresetProperty_Character {
            get {
                return ResourceManager.GetString("PresetProperty_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string PresetProperty_Developer {
            get {
                return ResourceManager.GetString("PresetProperty_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string PresetProperty_Director {
            get {
                return ResourceManager.GetString("PresetProperty_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string PresetProperty_Duration {
            get {
                return ResourceManager.GetString("PresetProperty_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpisodeCount.
        /// </summary>
        public static string PresetProperty_EpisodeCount {
            get {
                return ResourceManager.GetString("PresetProperty_EpisodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageCount.
        /// </summary>
        public static string PresetProperty_ImageCount {
            get {
                return ResourceManager.GetString("PresetProperty_ImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is3D.
        /// </summary>
        public static string PresetProperty_Is3D {
            get {
                return ResourceManager.GetString("PresetProperty_Is3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAi.
        /// </summary>
        public static string PresetProperty_IsAi {
            get {
                return ResourceManager.GetString("PresetProperty_IsAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCensored.
        /// </summary>
        public static string PresetProperty_IsCensored {
            get {
                return ResourceManager.GetString("PresetProperty_IsCensored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string PresetProperty_Language {
            get {
                return ResourceManager.GetString("PresetProperty_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PresetProperty_Name {
            get {
                return ResourceManager.GetString("PresetProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string PresetProperty_Original {
            get {
                return ResourceManager.GetString("PresetProperty_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string PresetProperty_Platform {
            get {
                return ResourceManager.GetString("PresetProperty_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string PresetProperty_Publisher {
            get {
                return ResourceManager.GetString("PresetProperty_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate.
        /// </summary>
        public static string PresetProperty_ReleaseDate {
            get {
                return ResourceManager.GetString("PresetProperty_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string PresetProperty_Resolution {
            get {
                return ResourceManager.GetString("PresetProperty_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string PresetProperty_Series {
            get {
                return ResourceManager.GetString("PresetProperty_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singer.
        /// </summary>
        public static string PresetProperty_Singer {
            get {
                return ResourceManager.GetString("PresetProperty_Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionPlatform.
        /// </summary>
        public static string PresetProperty_SubscriptionPlatform {
            get {
                return ResourceManager.GetString("PresetProperty_SubscriptionPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubtitleLanguage.
        /// </summary>
        public static string PresetProperty_SubtitleLanguage {
            get {
                return ResourceManager.GetString("PresetProperty_SubtitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string PresetProperty_Tag {
            get {
                return ResourceManager.GetString("PresetProperty_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PresetProperty_Type {
            get {
                return ResourceManager.GetString("PresetProperty_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoCodec.
        /// </summary>
        public static string PresetProperty_VideoCodec {
            get {
                return ResourceManager.GetString("PresetProperty_VideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceActor.
        /// </summary>
        public static string PresetProperty_VoiceActor {
            get {
                return ResourceManager.GetString("PresetProperty_VoiceActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdultMmd.
        /// </summary>
        public static string PresetResourceType_AdultMmd {
            get {
                return ResourceManager.GetString("PresetResourceType_AdultMmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiImage.
        /// </summary>
        public static string PresetResourceType_AiImage {
            get {
                return ResourceManager.GetString("PresetResourceType_AiImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AiVideo.
        /// </summary>
        public static string PresetResourceType_AiVideo {
            get {
                return ResourceManager.GetString("PresetResourceType_AiVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string PresetResourceType_Anime {
            get {
                return ResourceManager.GetString("PresetResourceType_Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string PresetResourceType_Application {
            get {
                return ResourceManager.GetString("PresetResourceType_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artbook.
        /// </summary>
        public static string PresetResourceType_Artbook {
            get {
                return ResourceManager.GetString("PresetResourceType_Artbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtistCg.
        /// </summary>
        public static string PresetResourceType_ArtistCg {
            get {
                return ResourceManager.GetString("PresetResourceType_ArtistCg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsmrAudio.
        /// </summary>
        public static string PresetResourceType_AsmrAudio {
            get {
                return ResourceManager.GetString("PresetResourceType_AsmrAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsmrVideo.
        /// </summary>
        public static string PresetResourceType_AsmrVideo {
            get {
                return ResourceManager.GetString("PresetResourceType_AsmrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string PresetResourceType_Audio {
            get {
                return ResourceManager.GetString("PresetResourceType_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AV.
        /// </summary>
        public static string PresetResourceType_Av {
            get {
                return ResourceManager.GetString("PresetResourceType_Av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVClip.
        /// </summary>
        public static string PresetResourceType_AvClip {
            get {
                return ResourceManager.GetString("PresetResourceType_AvClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVSubscription.
        /// </summary>
        public static string PresetResourceType_AvSubscription {
            get {
                return ResourceManager.GetString("PresetResourceType_AvSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        public static string PresetResourceType_Clip {
            get {
                return ResourceManager.GetString("PresetResourceType_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        public static string PresetResourceType_Comic {
            get {
                return ResourceManager.GetString("PresetResourceType_Comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosplay.
        /// </summary>
        public static string PresetResourceType_Cosplay {
            get {
                return ResourceManager.GetString("PresetResourceType_Cosplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        public static string PresetResourceType_Documentary {
            get {
                return ResourceManager.GetString("PresetResourceType_Documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doushijin.
        /// </summary>
        public static string PresetResourceType_Doushijin {
            get {
                return ResourceManager.GetString("PresetResourceType_Doushijin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galgame.
        /// </summary>
        public static string PresetResourceType_Galgame {
            get {
                return ResourceManager.GetString("PresetResourceType_Galgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string PresetResourceType_Game {
            get {
                return ResourceManager.GetString("PresetResourceType_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameCg.
        /// </summary>
        public static string PresetResourceType_GameCg {
            get {
                return ResourceManager.GetString("PresetResourceType_GameCg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration.
        /// </summary>
        public static string PresetResourceType_Illustration {
            get {
                return ResourceManager.GetString("PresetResourceType_Illustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IllustrationSubscription.
        /// </summary>
        public static string PresetResourceType_IllustrationSubscription {
            get {
                return ResourceManager.GetString("PresetResourceType_IllustrationSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string PresetResourceType_Image {
            get {
                return ResourceManager.GetString("PresetResourceType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageSubscription.
        /// </summary>
        public static string PresetResourceType_ImageSubscription {
            get {
                return ResourceManager.GetString("PresetResourceType_ImageSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveStream.
        /// </summary>
        public static string PresetResourceType_LiveStream {
            get {
                return ResourceManager.GetString("PresetResourceType_LiveStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga.
        /// </summary>
        public static string PresetResourceType_Manga {
            get {
                return ResourceManager.GetString("PresetResourceType_Manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga3D.
        /// </summary>
        public static string PresetResourceType_Manga3D {
            get {
                return ResourceManager.GetString("PresetResourceType_Manga3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MangaSubscription.
        /// </summary>
        public static string PresetResourceType_MangaSubscription {
            get {
                return ResourceManager.GetString("PresetResourceType_MangaSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMD.
        /// </summary>
        public static string PresetResourceType_Mmd {
            get {
                return ResourceManager.GetString("PresetResourceType_Mmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string PresetResourceType_Mod {
            get {
                return ResourceManager.GetString("PresetResourceType_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotionManga.
        /// </summary>
        public static string PresetResourceType_MotionManga {
            get {
                return ResourceManager.GetString("PresetResourceType_MotionManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string PresetResourceType_Movie {
            get {
                return ResourceManager.GetString("PresetResourceType_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string PresetResourceType_Music {
            get {
                return ResourceManager.GetString("PresetResourceType_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel.
        /// </summary>
        public static string PresetResourceType_Novel {
            get {
                return ResourceManager.GetString("PresetResourceType_Novel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ova.
        /// </summary>
        public static string PresetResourceType_Ova {
            get {
                return ResourceManager.GetString("PresetResourceType_Ova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photograph.
        /// </summary>
        public static string PresetResourceType_Photograph {
            get {
                return ResourceManager.GetString("PresetResourceType_Photograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast.
        /// </summary>
        public static string PresetResourceType_Podcast {
            get {
                return ResourceManager.GetString("PresetResourceType_Podcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string PresetResourceType_Text {
            get {
                return ResourceManager.GetString("PresetResourceType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string PresetResourceType_Tool {
            get {
                return ResourceManager.GetString("PresetResourceType_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TvSeries.
        /// </summary>
        public static string PresetResourceType_TvSeries {
            get {
                return ResourceManager.GetString("PresetResourceType_TvSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TvShow.
        /// </summary>
        public static string PresetResourceType_TvShow {
            get {
                return ResourceManager.GetString("PresetResourceType_TvShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string PresetResourceType_Video {
            get {
                return ResourceManager.GetString("PresetResourceType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoSubscription.
        /// </summary>
        public static string PresetResourceType_VideoSubscription {
            get {
                return ResourceManager.GetString("PresetResourceType_VideoSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR.
        /// </summary>
        public static string PresetResourceType_Vr {
            get {
                return ResourceManager.GetString("PresetResourceType_Vr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR Anime.
        /// </summary>
        public static string PresetResourceType_VrAnime {
            get {
                return ResourceManager.GetString("PresetResourceType_VrAnime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR AV.
        /// </summary>
        public static string PresetResourceType_VrAv {
            get {
                return ResourceManager.GetString("PresetResourceType_VrAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR Game.
        /// </summary>
        public static string PresetResourceType_VrGame {
            get {
                return ResourceManager.GetString("PresetResourceType_VrGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        public static string PresetResourceTypeDescription_Comic {
            get {
                return ResourceManager.GetString("PresetResourceTypeDescription_Comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga.
        /// </summary>
        public static string PresetResourceTypeDescription_Manga {
            get {
                return ResourceManager.GetString("PresetResourceTypeDescription_Manga", resourceCulture);
            }
        }
    }
}
