name: Checkout All Repos
description: Checkout main repo and all dependencies
runs:
  using: "composite"
  steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: ${{ github.event.repository.name }}
    - name: Clone Bakabase.Infrastructures
      run: git clone https://github.com/anobaka/Bakabase.Infrastructures.git
      shell: bash
    - name: Clone LazyMortal
      run: git clone https://github.com/anobaka/LazyMortal.git
      shell: bash