//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.InsideWorld.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DownloaderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DownloaderResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.InsideWorld.Business.Resources.DownloaderResource", typeof(DownloaderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free disk space to write {0}. Free up space, then run the task again; downloaded parts are kept and resumed..
        /// </summary>
        internal static string Bilibili_DiskFull {
            get {
                return ResourceManager.GetString("Bilibili.DiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Bilibili_Favorites {
            get {
                return ResourceManager.GetString("Bilibili.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download videos from your Bilibili favorite collections.
        /// </summary>
        internal static string Bilibili_Favorites_Description {
            get {
                return ResourceManager.GetString("Bilibili.Favorites.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili favorites folder {0} ({1}) was not found in this account. It may have been deleted, or the cookie belongs to another account..
        /// </summary>
        internal static string Bilibili_FavoritesNotFound {
            get {
                return ResourceManager.GetString("Bilibili.FavoritesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bilibili cookie is not logged in or has expired. Update it in the downloader settings, then run the task again..
        /// </summary>
        internal static string Bilibili_NotLoggedIn {
            get {
                return ResourceManager.GetString("Bilibili.NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili is temporarily refusing requests (risk control, code {0}). The task retries automatically; if it keeps failing, wait a while or update the cookie..
        /// </summary>
        internal static string Bilibili_RiskControl {
            get {
                return ResourceManager.GetString("Bilibili.RiskControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili is refusing requests for now (risk control); retrying in {0} min ({1}/{2}).
        /// </summary>
        internal static string Bilibili_RiskControlWaiting {
            get {
                return ResourceManager.GetString("Bilibili.RiskControlWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this account has no access.
        /// </summary>
        internal static string Bilibili_Skip_AccessDenied {
            get {
                return ResourceManager.GetString("Bilibili.Skip.AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no Bilibili CDN server would deliver the video (HTTP {0}); it may work later.
        /// </summary>
        internal static string Bilibili_Skip_CdnUnavailable {
            get {
                return ResourceManager.GetString("Bilibili.Skip.CdnUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted or no longer visible.
        /// </summary>
        internal static string Bilibili_Skip_Deleted {
            get {
                return ResourceManager.GetString("Bilibili.Skip.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interactive videos are not supported.
        /// </summary>
        internal static string Bilibili_Skip_InteractiveVideo {
            get {
                return ResourceManager.GetString("Bilibili.Skip.InteractiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no longer available (removed or invalidated).
        /// </summary>
        internal static string Bilibili_Skip_InvalidItem {
            get {
                return ResourceManager.GetString("Bilibili.Skip.InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg could not merge the video and audio (exit code {0}).
        /// </summary>
        internal static string Bilibili_Skip_MergeFailed {
            get {
                return ResourceManager.GetString("Bilibili.Skip.MergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bangumi/film episode, not supported yet (it may need a membership).
        /// </summary>
        internal static string Bilibili_Skip_PgcEpisodeNotSupported {
            get {
                return ResourceManager.GetString("Bilibili.Skip.PgcEpisodeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bangumi/film episode that needs a membership or purchase (not supported yet).
        /// </summary>
        internal static string Bilibili_Skip_PgcMemberOrPaid {
            get {
                return ResourceManager.GetString("Bilibili.Skip.PgcMemberOrPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this account only gets a preview, which was not saved.
        /// </summary>
        internal static string Bilibili_Skip_PreviewOnly {
            get {
                return ResourceManager.GetString("Bilibili.Skip.PreviewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only visible to the uploader.
        /// </summary>
        internal static string Bilibili_Skip_PrivateToUploader {
            get {
                return ResourceManager.GetString("Bilibili.Skip.PrivateToUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available in your region, or hidden.
        /// </summary>
        internal static string Bilibili_Skip_RegionRestrictedOrHidden {
            get {
                return ResourceManager.GetString("Bilibili.Skip.RegionRestrictedOrHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supporter-only (充电专属) video; this account has no access.
        /// </summary>
        internal static string Bilibili_Skip_SupporterOnly {
            get {
                return ResourceManager.GetString("Bilibili.Skip.SupporterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supporter-only video; this account only gets a preview, which was not saved.
        /// </summary>
        internal static string Bilibili_Skip_SupporterOnlyPreview {
            get {
                return ResourceManager.GetString("Bilibili.Skip.SupporterOnlyPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unavailable on Bilibili (code {0}) {1}.
        /// </summary>
        internal static string Bilibili_Skip_Unavailable {
            get {
                return ResourceManager.GetString("Bilibili.Skip.Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under review.
        /// </summary>
        internal static string Bilibili_Skip_UnderReview {
            get {
                return ResourceManager.GetString("Bilibili.Skip.UnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio items are not supported yet.
        /// </summary>
        internal static string Bilibili_Skip_UnsupportedAudio {
            get {
                return ResourceManager.GetString("Bilibili.Skip.UnsupportedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video collections are not supported yet.
        /// </summary>
        internal static string Bilibili_Skip_UnsupportedCollection {
            get {
                return ResourceManager.GetString("Bilibili.Skip.UnsupportedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported favorites item type {0}.
        /// </summary>
        internal static string Bilibili_Skip_UnsupportedItemType {
            get {
                return ResourceManager.GetString("Bilibili.Skip.UnsupportedItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bangumi/film episodes are not supported yet.
        /// </summary>
        internal static string Bilibili_Skip_UnsupportedOgvEpisode {
            get {
                return ResourceManager.GetString("Bilibili.Skip.UnsupportedOgvEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped items are not retried automatically, and the log lists every one. To check them again, clear this task's checkpoint..
        /// </summary>
        internal static string Bilibili_SkipFooter {
            get {
                return ResourceManager.GetString("Bilibili.SkipFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — skipped: {1}.
        /// </summary>
        internal static string Bilibili_SkipNotice {
            get {
                return ResourceManager.GetString("Bilibili.SkipNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string BilibiliDownloadTaskType_Favorites {
            get {
                return ResourceManager.GetString("BilibiliDownloadTaskType.Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AV ID.
        /// </summary>
        internal static string BilibiliNamingFields_AId {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.AId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BV ID.
        /// </summary>
        internal static string BilibiliNamingFields_BvId {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.BvId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C ID.
        /// </summary>
        internal static string BilibiliNamingFields_CId {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.CId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string BilibiliNamingFields_Extension {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        internal static string BilibiliNamingFields_PartName {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string BilibiliNamingFields_PartNo {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.PartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Title.
        /// </summary>
        internal static string BilibiliNamingFields_PostTitle {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Name.
        /// </summary>
        internal static string BilibiliNamingFields_QualityName {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.QualityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader ID.
        /// </summary>
        internal static string BilibiliNamingFields_UploaderId {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.UploaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader Name.
        /// </summary>
        internal static string BilibiliNamingFields_UploaderName {
            get {
                return ResourceManager.GetString("BilibiliNamingFields.UploaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Cien_Creator {
            get {
                return ResourceManager.GetString("Cien.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all posts from a specific Ci-en creator.
        /// </summary>
        internal static string Cien_Creator_Description {
            get {
                return ResourceManager.GetString("Cien.Creator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Cien_Following {
            get {
                return ResourceManager.GetString("Cien.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download posts from Ci-en creators you follow.
        /// </summary>
        internal static string Cien_Following_Description {
            get {
                return ResourceManager.GetString("Cien.Following.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string Cien_SinglePost {
            get {
                return ResourceManager.GetString("Cien.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a specific Ci-en post by ID.
        /// </summary>
        internal static string Cien_SinglePost_Description {
            get {
                return ResourceManager.GetString("Cien.SinglePost.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string CienDownloadTaskType_Creator {
            get {
                return ResourceManager.GetString("CienDownloadTaskType.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string CienDownloadTaskType_Following {
            get {
                return ResourceManager.GetString("CienDownloadTaskType.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string CienDownloadTaskType_SinglePost {
            get {
                return ResourceManager.GetString("CienDownloadTaskType.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article ID.
        /// </summary>
        internal static string CienNamingFields_ArticleId {
            get {
                return ResourceManager.GetString("CienNamingFields.ArticleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Title.
        /// </summary>
        internal static string CienNamingFields_ArticleTitle {
            get {
                return ResourceManager.GetString("CienNamingFields.ArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        internal static string CienNamingFields_AuthorId {
            get {
                return ResourceManager.GetString("CienNamingFields.AuthorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        internal static string CienNamingFields_AuthorName {
            get {
                return ResourceManager.GetString("CienNamingFields.AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string CienNamingFields_Extension {
            get {
                return ResourceManager.GetString("CienNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        internal static string CienNamingFields_FileNo {
            get {
                return ResourceManager.GetString("CienNamingFields.FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string CienNamingFields_PublishDate {
            get {
                return ResourceManager.GetString("CienNamingFields.PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili.
        /// </summary>
        internal static string DownloaderSource_Bilibili {
            get {
                return ResourceManager.GetString("DownloaderSource.Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ci-en.
        /// </summary>
        internal static string DownloaderSource_Cien {
            get {
                return ResourceManager.GetString("DownloaderSource.Cien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExHentai.
        /// </summary>
        internal static string DownloaderSource_ExHentai {
            get {
                return ResourceManager.GetString("DownloaderSource.ExHentai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanbox.
        /// </summary>
        internal static string DownloaderSource_Fanbox {
            get {
                return ResourceManager.GetString("DownloaderSource.Fanbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantia.
        /// </summary>
        internal static string DownloaderSource_Fantia {
            get {
                return ResourceManager.GetString("DownloaderSource.Fantia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon.
        /// </summary>
        internal static string DownloaderSource_Patreon {
            get {
                return ResourceManager.GetString("DownloaderSource.Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixiv.
        /// </summary>
        internal static string DownloaderSource_Pixiv {
            get {
                return ResourceManager.GetString("DownloaderSource.Pixiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} note(s) from this task:.
        /// </summary>
        internal static string DownloadNotices_Summary {
            get {
                return ResourceManager.GetString("DownloadNotices.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …and {0} more (see the log for the full list).
        /// </summary>
        internal static string DownloadNotices_Truncated {
            get {
                return ResourceManager.GetString("DownloadNotices.Truncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download path not set.
        /// </summary>
        internal static string DownloadPathNotSet {
            get {
                return ResourceManager.GetString("DownloadPathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ExHentai_List {
            get {
                return ResourceManager.GetString("ExHentai.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download galleries from ExHentai search results or lists.
        /// </summary>
        internal static string ExHentai_List_Description {
            get {
                return ResourceManager.GetString("ExHentai.List.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Work.
        /// </summary>
        internal static string ExHentai_SingleWork {
            get {
                return ResourceManager.GetString("ExHentai.SingleWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a single gallery or work from ExHentai.
        /// </summary>
        internal static string ExHentai_SingleWork_Description {
            get {
                return ResourceManager.GetString("ExHentai.SingleWork.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string ExHentai_Torrent {
            get {
                return ResourceManager.GetString("ExHentai.Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download ExHentai content via torrent files.
        /// </summary>
        internal static string ExHentai_Torrent_Description {
            get {
                return ResourceManager.GetString("ExHentai.Torrent.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        internal static string ExHentai_Watched {
            get {
                return ResourceManager.GetString("ExHentai.Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download galleries from your ExHentai watched list.
        /// </summary>
        internal static string ExHentai_Watched_Description {
            get {
                return ResourceManager.GetString("ExHentai.Watched.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ExHentaiDownloadTaskType_List {
            get {
                return ResourceManager.GetString("ExHentaiDownloadTaskType.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Work.
        /// </summary>
        internal static string ExHentaiDownloadTaskType_SingleWork {
            get {
                return ResourceManager.GetString("ExHentaiDownloadTaskType.SingleWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string ExHentaiDownloadTaskType_Torrent {
            get {
                return ResourceManager.GetString("ExHentaiDownloadTaskType.Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        internal static string ExHentaiDownloadTaskType_Watched {
            get {
                return ResourceManager.GetString("ExHentaiDownloadTaskType.Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ExHentaiNamingFields_Category {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string ExHentaiNamingFields_Extension {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery ID.
        /// </summary>
        internal static string ExHentaiNamingFields_GalleryId {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.GalleryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Token.
        /// </summary>
        internal static string ExHentaiNamingFields_GalleryToken {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.GalleryToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExHentaiNamingFields_Name {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        internal static string ExHentaiNamingFields_PageTitle {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Name.
        /// </summary>
        internal static string ExHentaiNamingFields_RawName {
            get {
                return ResourceManager.GetString("ExHentaiNamingFields.RawName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Fanbox_Creator {
            get {
                return ResourceManager.GetString("Fanbox.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all posts from a specific Fanbox creator.
        /// </summary>
        internal static string Fanbox_Creator_Description {
            get {
                return ResourceManager.GetString("Fanbox.Creator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Fanbox_Following {
            get {
                return ResourceManager.GetString("Fanbox.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download posts from Fanbox creators you follow.
        /// </summary>
        internal static string Fanbox_Following_Description {
            get {
                return ResourceManager.GetString("Fanbox.Following.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string Fanbox_SinglePost {
            get {
                return ResourceManager.GetString("Fanbox.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a specific Fanbox post by ID.
        /// </summary>
        internal static string Fanbox_SinglePost_Description {
            get {
                return ResourceManager.GetString("Fanbox.SinglePost.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string FanboxDownloadTaskType_Creator {
            get {
                return ResourceManager.GetString("FanboxDownloadTaskType.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string FanboxDownloadTaskType_Following {
            get {
                return ResourceManager.GetString("FanboxDownloadTaskType.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string FanboxDownloadTaskType_SinglePost {
            get {
                return ResourceManager.GetString("FanboxDownloadTaskType.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator ID.
        /// </summary>
        internal static string FanboxNamingFields_CreatorId {
            get {
                return ResourceManager.GetString("FanboxNamingFields.CreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator Name.
        /// </summary>
        internal static string FanboxNamingFields_CreatorName {
            get {
                return ResourceManager.GetString("FanboxNamingFields.CreatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string FanboxNamingFields_Extension {
            get {
                return ResourceManager.GetString("FanboxNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        internal static string FanboxNamingFields_FileNo {
            get {
                return ResourceManager.GetString("FanboxNamingFields.FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post ID.
        /// </summary>
        internal static string FanboxNamingFields_PostId {
            get {
                return ResourceManager.GetString("FanboxNamingFields.PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Title.
        /// </summary>
        internal static string FanboxNamingFields_PostTitle {
            get {
                return ResourceManager.GetString("FanboxNamingFields.PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string FanboxNamingFields_PublishDate {
            get {
                return ResourceManager.GetString("FanboxNamingFields.PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Fantia_Creator {
            get {
                return ResourceManager.GetString("Fantia.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all posts from a specific Fantia creator.
        /// </summary>
        internal static string Fantia_Creator_Description {
            get {
                return ResourceManager.GetString("Fantia.Creator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Fantia_Following {
            get {
                return ResourceManager.GetString("Fantia.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download posts from Fantia creators you follow.
        /// </summary>
        internal static string Fantia_Following_Description {
            get {
                return ResourceManager.GetString("Fantia.Following.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string Fantia_SinglePost {
            get {
                return ResourceManager.GetString("Fantia.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a specific Fantia post by ID.
        /// </summary>
        internal static string Fantia_SinglePost_Description {
            get {
                return ResourceManager.GetString("Fantia.SinglePost.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string FantiaDownloadTaskType_Creator {
            get {
                return ResourceManager.GetString("FantiaDownloadTaskType.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string FantiaDownloadTaskType_Following {
            get {
                return ResourceManager.GetString("FantiaDownloadTaskType.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string FantiaDownloadTaskType_SinglePost {
            get {
                return ResourceManager.GetString("FantiaDownloadTaskType.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string FantiaNamingFields_Extension {
            get {
                return ResourceManager.GetString("FantiaNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanclub ID.
        /// </summary>
        internal static string FantiaNamingFields_FanclubId {
            get {
                return ResourceManager.GetString("FantiaNamingFields.FanclubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanclub Name.
        /// </summary>
        internal static string FantiaNamingFields_FanclubName {
            get {
                return ResourceManager.GetString("FantiaNamingFields.FanclubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        internal static string FantiaNamingFields_FileNo {
            get {
                return ResourceManager.GetString("FantiaNamingFields.FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post ID.
        /// </summary>
        internal static string FantiaNamingFields_PostId {
            get {
                return ResourceManager.GetString("FantiaNamingFields.PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Title.
        /// </summary>
        internal static string FantiaNamingFields_PostTitle {
            get {
                return ResourceManager.GetString("FantiaNamingFields.PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string FantiaNamingFields_PublishDate {
            get {
                return ResourceManager.GetString("FantiaNamingFields.PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg is not ready.
        /// </summary>
        internal static string FfMpegIsNotReady {
            get {
                return ResourceManager.GetString("FfMpegIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cookie.
        /// </summary>
        internal static string InvalidCookie {
            get {
                return ResourceManager.GetString("InvalidCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid favorites.
        /// </summary>
        internal static string InvalidFavorites {
            get {
                return ResourceManager.GetString("InvalidFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Patreon_Creator {
            get {
                return ResourceManager.GetString("Patreon.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all posts from a specific Patreon creator.
        /// </summary>
        internal static string Patreon_Creator_Description {
            get {
                return ResourceManager.GetString("Patreon.Creator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Patreon_Following {
            get {
                return ResourceManager.GetString("Patreon.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download posts from Patreon creators you follow.
        /// </summary>
        internal static string Patreon_Following_Description {
            get {
                return ResourceManager.GetString("Patreon.Following.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string Patreon_SinglePost {
            get {
                return ResourceManager.GetString("Patreon.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a specific Patreon post by ID.
        /// </summary>
        internal static string Patreon_SinglePost_Description {
            get {
                return ResourceManager.GetString("Patreon.SinglePost.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string PatreonDownloadTaskType_Creator {
            get {
                return ResourceManager.GetString("PatreonDownloadTaskType.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string PatreonDownloadTaskType_Following {
            get {
                return ResourceManager.GetString("PatreonDownloadTaskType.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Post.
        /// </summary>
        internal static string PatreonDownloadTaskType_SinglePost {
            get {
                return ResourceManager.GetString("PatreonDownloadTaskType.SinglePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator ID.
        /// </summary>
        internal static string PatreonNamingFields_CreatorId {
            get {
                return ResourceManager.GetString("PatreonNamingFields.CreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator Name.
        /// </summary>
        internal static string PatreonNamingFields_CreatorName {
            get {
                return ResourceManager.GetString("PatreonNamingFields.CreatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string PatreonNamingFields_Extension {
            get {
                return ResourceManager.GetString("PatreonNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        internal static string PatreonNamingFields_FileNo {
            get {
                return ResourceManager.GetString("PatreonNamingFields.FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post ID.
        /// </summary>
        internal static string PatreonNamingFields_PostId {
            get {
                return ResourceManager.GetString("PatreonNamingFields.PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Title.
        /// </summary>
        internal static string PatreonNamingFields_PostTitle {
            get {
                return ResourceManager.GetString("PatreonNamingFields.PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string PatreonNamingFields_PublishDate {
            get {
                return ResourceManager.GetString("PatreonNamingFields.PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier Level.
        /// </summary>
        internal static string PatreonNamingFields_TierLevel {
            get {
                return ResourceManager.GetString("PatreonNamingFields.TierLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Pixiv_Following {
            get {
                return ResourceManager.GetString("Pixiv.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest illustrations from artists you follow.
        /// </summary>
        internal static string Pixiv_Following_Description {
            get {
                return ResourceManager.GetString("Pixiv.Following.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string Pixiv_Ranking {
            get {
                return ResourceManager.GetString("Pixiv.Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download illustrations from Pixiv daily rankings.
        /// </summary>
        internal static string Pixiv_Ranking_Description {
            get {
                return ResourceManager.GetString("Pixiv.Ranking.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Pixiv_Search {
            get {
                return ResourceManager.GetString("Pixiv.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download illustrations from Pixiv search results.
        /// </summary>
        internal static string Pixiv_Search_Description {
            get {
                return ResourceManager.GetString("Pixiv.Search.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string PixivDownloadTaskType_Following {
            get {
                return ResourceManager.GetString("PixivDownloadTaskType.Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string PixivDownloadTaskType_Ranking {
            get {
                return ResourceManager.GetString("PixivDownloadTaskType.Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string PixivDownloadTaskType_Search {
            get {
                return ResourceManager.GetString("PixivDownloadTaskType.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string PixivNamingFields_Extension {
            get {
                return ResourceManager.GetString("PixivNamingFields.Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration ID.
        /// </summary>
        internal static string PixivNamingFields_IllustrationId {
            get {
                return ResourceManager.GetString("PixivNamingFields.IllustrationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration Title.
        /// </summary>
        internal static string PixivNamingFields_IllustrationTitle {
            get {
                return ResourceManager.GetString("PixivNamingFields.IllustrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number.
        /// </summary>
        internal static string PixivNamingFields_PageNo {
            get {
                return ResourceManager.GetString("PixivNamingFields.PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string PixivNamingFields_Tags {
            get {
                return ResourceManager.GetString("PixivNamingFields.Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date.
        /// </summary>
        internal static string PixivNamingFields_UploadDate {
            get {
                return ResourceManager.GetString("PixivNamingFields.UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string PixivNamingFields_UserId {
            get {
                return ResourceManager.GetString("PixivNamingFields.UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string PixivNamingFields_UserName {
            get {
                return ResourceManager.GetString("PixivNamingFields.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error, retrying in {0}s ({1}/{2}).
        /// </summary>
        internal static string TransientNetworkErrorRetrying {
            get {
                return ResourceManager.GetString("TransientNetworkErrorRetrying", resourceCulture);
            }
        }
    }
}
