//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.InsideWorld.Business.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bakabase.InsideWorld.Business.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Category_ComponentWithTypeHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("Category_ComponentWithTypeHasNotBeenConfigured", resourceCulture);
            }
        }
        
        internal static string Category_Invalid {
            get {
                return ResourceManager.GetString("Category_Invalid", resourceCulture);
            }
        }
        
        internal static string Category_MediaLibraryExistsOnDeletion {
            get {
                return ResourceManager.GetString("Category_MediaLibraryExistsOnDeletion", resourceCulture);
            }
        }
        
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        internal static string Component_DuplicatesAreFound {
            get {
                return ResourceManager.GetString("Component_DuplicatesAreFound", resourceCulture);
            }
        }
        
        internal static string Component_Invalid {
            get {
                return ResourceManager.GetString("Component_Invalid", resourceCulture);
            }
        }
        
        internal static string Component_KeyCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Component_KeyCanNotBeEmpty", resourceCulture);
            }
        }
        
        internal static string Component_NotDeletableWhenUsingByCategories {
            get {
                return ResourceManager.GetString("Component_NotDeletableWhenUsingByCategories", resourceCulture);
            }
        }
        
        internal static string Component_OptionsAppliedToWrongTypeDescriptor {
            get {
                return ResourceManager.GetString("Component_OptionsAppliedToWrongTypeDescriptor", resourceCulture);
            }
        }
        
        internal static string Component_OptionsAreNotConfigured {
            get {
                return ResourceManager.GetString("Component_OptionsAreNotConfigured", resourceCulture);
            }
        }
        
        internal static string Component_OptionsWithIdAreNotFound {
            get {
                return ResourceManager.GetString("Component_OptionsWithIdAreNotFound", resourceCulture);
            }
        }
        
        internal static string Component_TypeMismatch {
            get {
                return ResourceManager.GetString("Component_TypeMismatch", resourceCulture);
            }
        }
        
        internal static string CookieValidation_Fail {
            get {
                return ResourceManager.GetString("CookieValidation_Fail", resourceCulture);
            }
        }
        
        internal static string CustomProperty_DescriptorNotFound {
            get {
                return ResourceManager.GetString("CustomProperty_DescriptorNotFound", resourceCulture);
            }
        }
        
        internal static string Downloader_BilibiliCookieIsInvalid {
            get {
                return ResourceManager.GetString("Downloader_BilibiliCookieIsInvalid", resourceCulture);
            }
        }
        
        internal static string Downloader_BilibiliFavoritesIsMissing {
            get {
                return ResourceManager.GetString("Downloader_BilibiliFavoritesIsMissing", resourceCulture);
            }
        }
        
        internal static string Downloader_DownloaderCountExceeded {
            get {
                return ResourceManager.GetString("Downloader_DownloaderCountExceeded", resourceCulture);
            }
        }
        
        internal static string Downloader_DownloaderOptionsValidatorNotRegistered {
            get {
                return ResourceManager.GetString("Downloader_DownloaderOptionsValidatorNotRegistered", resourceCulture);
            }
        }
        
        internal static string Downloader_FailedToStart {
            get {
                return ResourceManager.GetString("Downloader_FailedToStart", resourceCulture);
            }
        }
        
        internal static string Downloader_KeyIsMissing {
            get {
                return ResourceManager.GetString("Downloader_KeyIsMissing", resourceCulture);
            }
        }
        
        internal static string Downloader_MayBeDuplicate {
            get {
                return ResourceManager.GetString("Downloader_MayBeDuplicate", resourceCulture);
            }
        }
        
        internal static string Downloader_UnknownThirdPartyId {
            get {
                return ResourceManager.GetString("Downloader_UnknownThirdPartyId", resourceCulture);
            }
        }
        
        internal static string Downloader_UnknownType {
            get {
                return ResourceManager.GetString("Downloader_UnknownType", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string FileDoesNotExistInPath {
            get {
                return ResourceManager.GetString("FileDoesNotExistInPath", resourceCulture);
            }
        }
        
        internal static string FileMover_DuplicateSourcesAreFound {
            get {
                return ResourceManager.GetString("FileMover_DuplicateSourcesAreFound", resourceCulture);
            }
        }
        
        internal static string FileMover_DuplicateTargetsAreFound {
            get {
                return ResourceManager.GetString("FileMover_DuplicateTargetsAreFound", resourceCulture);
            }
        }
        
        internal static string FileMover_SourcesCantBeSubOfSources {
            get {
                return ResourceManager.GetString("FileMover_SourcesCantBeSubOfSources", resourceCulture);
            }
        }
        
        internal static string FileMover_TargetsCantBeSubOfSources {
            get {
                return ResourceManager.GetString("FileMover_TargetsCantBeSubOfSources", resourceCulture);
            }
        }
        
        internal static string FilesDoNotExistInPath {
            get {
                return ResourceManager.GetString("FilesDoNotExistInPath", resourceCulture);
            }
        }
        
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_CustomProperty {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_CustomProperty", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Favorites {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Favorites", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Language {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Language", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Name {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Name", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Original {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Original", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Publisher {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Publisher", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_ReleaseDt {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_ReleaseDt", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Series {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Series", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Tag {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Tag", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Volume_Index {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Volume_Index", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Volume_Name {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Volume_Name", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Volume_Title {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Volume_Title", resourceCulture);
            }
        }
        
        internal static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        internal static string PathIsNotFound {
            get {
                return ResourceManager.GetString("PathIsNotFound", resourceCulture);
            }
        }
        
        internal static string PathsShouldBeInSameDirectory {
            get {
                return ResourceManager.GetString("PathsShouldBeInSameDirectory", resourceCulture);
            }
        }
        
        internal static string Resource_CannotSaveCoverToCurrentDirectoryForSingleFileResource {
            get {
                return ResourceManager.GetString("Resource_CannotSaveCoverToCurrentDirectoryForSingleFileResource", resourceCulture);
            }
        }
        
        internal static string Resource_CoverMustBeInDirectory {
            get {
                return ResourceManager.GetString("Resource_CoverMustBeInDirectory", resourceCulture);
            }
        }
        
        internal static string Resource_MovingTaskSummary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummary", resourceCulture);
            }
        }
        
        internal static string Resource_MovingTaskSummaryForSingleResource {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryForSingleResource", resourceCulture);
            }
        }
        
        internal static string Resource_MovingTaskSummaryForSingleResourceWithMediaLibrary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryForSingleResourceWithMediaLibrary", resourceCulture);
            }
        }
        
        internal static string Resource_MovingTaskSummaryWithMediaLibrary {
            get {
                return ResourceManager.GetString("Resource_MovingTaskSummaryWithMediaLibrary", resourceCulture);
            }
        }
        
        internal static string Resource_NotFound {
            get {
                return ResourceManager.GetString("Resource_NotFound", resourceCulture);
            }
        }
        
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        internal static string TypeIsNotFound {
            get {
                return ResourceManager.GetString("TypeIsNotFound", resourceCulture);
            }
        }
        
        internal static string ValueIsNotSet {
            get {
                return ResourceManager.GetString("ValueIsNotSet", resourceCulture);
            }
        }
        
        internal static string Migration_V190_DefaultPropertyName_Cover {
            get {
                return ResourceManager.GetString("Migration_V190_DefaultPropertyName_Cover", resourceCulture);
            }
        }
        
        internal static string Reserved_Resource_Property_Name_Introduction {
            get {
                return ResourceManager.GetString("Reserved_Resource_Property_Name_Introduction", resourceCulture);
            }
        }
        
        internal static string Reserved_Resource_Property_Name_Rating {
            get {
                return ResourceManager.GetString("Reserved_Resource_Property_Name_Rating", resourceCulture);
            }
        }
        
        internal static string Resource_Property_Reserved_Introduction_Name {
            get {
                return ResourceManager.GetString("Resource_Property_Reserved_Introduction_Name", resourceCulture);
            }
        }
        
        internal static string Resource_Property_Reserved_Rating_Name {
            get {
                return ResourceManager.GetString("Resource_Property_Reserved_Rating_Name", resourceCulture);
            }
        }
        
        internal static string Property_DescriptorIsNotFound {
            get {
                return ResourceManager.GetString("Property_DescriptorIsNotFound", resourceCulture);
            }
        }
        
        internal static string BuiltinPropertyForDisplayName_Filename {
            get {
                return ResourceManager.GetString("BuiltinPropertyForDisplayName.Filename", resourceCulture);
            }
        }
        
        internal static string Dependency_Component_ffmpeg_Name {
            get {
                return ResourceManager.GetString("Dependency_Component_ffmpeg_Name", resourceCulture);
            }
        }
        
        internal static string Dependency_Component_lux_Name {
            get {
                return ResourceManager.GetString("Dependency_Component_lux_Name", resourceCulture);
            }
        }
        
        internal static string Dependency_Component_ffmpeg_Description {
            get {
                return ResourceManager.GetString("Dependency_Component_ffmpeg_Description", resourceCulture);
            }
        }
        
        internal static string Dependency_Component_lux_Description {
            get {
                return ResourceManager.GetString("Dependency_Component_lux_Description", resourceCulture);
            }
        }
        
        internal static string Dependency_Component_Bakabase_Updater_Description {
            get {
                return ResourceManager.GetString("Dependency_Component_Bakabase.Updater_Description", resourceCulture);
            }
        }
        
        internal static string Dependency_Component_Bakabase_Updater_Name {
            get {
                return ResourceManager.GetString("Dependency_Component_Bakabase.Updater_Name", resourceCulture);
            }
        }
        
        internal static string BackgroundTask_PrepareCache_Name {
            get {
                return ResourceManager.GetString("BackgroundTask_PrepareCache_Name", resourceCulture);
            }
        }
        
        internal static string BackgroundTask_SyncMediaLibrary_Name {
            get {
                return ResourceManager.GetString("BackgroundTask_SyncMediaLibrary_Name", resourceCulture);
            }
        }
        
        internal static string BackgroundTask_MoveFiles_Name {
            get {
                return ResourceManager.GetString("BackgroundTask_MoveFiles_Name", resourceCulture);
            }
        }
        
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        internal static string BackgroundTask_Enhance_Name {
            get {
                return ResourceManager.GetString("BackgroundTask_Enhance_Name", resourceCulture);
            }
        }
        
        internal static string Decompress {
            get {
                return ResourceManager.GetString("Decompress", resourceCulture);
            }
        }
        
        internal static string MoveFiles {
            get {
                return ResourceManager.GetString("MoveFiles", resourceCulture);
            }
        }
        
        internal static string BTask_Name_Enhancement {
            get {
                return ResourceManager.GetString("BTask_Name_Enhancement", resourceCulture);
            }
        }
        
        internal static string BTask_Description_Enhancement {
            get {
                return ResourceManager.GetString("BTask_Description_Enhancement", resourceCulture);
            }
        }
        
        internal static string BTask_Name_PrepareCache {
            get {
                return ResourceManager.GetString("BTask_Name_PrepareCache", resourceCulture);
            }
        }
        
        internal static string BTask_Name_MoveFiles {
            get {
                return ResourceManager.GetString("BTask_Name_MoveFiles", resourceCulture);
            }
        }
        
        internal static string BTask_Description_PrepareCache {
            get {
                return ResourceManager.GetString("BTask_Description_PrepareCache", resourceCulture);
            }
        }
        
        internal static string BTask_MessageOnInterruption_MoveFiles {
            get {
                return ResourceManager.GetString("BTask_MessageOnInterruption_MoveFiles", resourceCulture);
            }
        }
        
        internal static string BTask_FailedToRunTaskDueToConflict {
            get {
                return ResourceManager.GetString("BTask_FailedToRunTaskDueToConflict", resourceCulture);
            }
        }
        
        internal static string BTask_FailedToRunTaskDueToUnknownTaskId {
            get {
                return ResourceManager.GetString("BTask_FailedToRunTaskDueToUnknownTaskId", resourceCulture);
            }
        }
        
        internal static string BTask_FailedToRunTaskDueToIdExisting {
            get {
                return ResourceManager.GetString("BTask_FailedToRunTaskDueToIdExisting", resourceCulture);
            }
        }
        
        internal static string MoveFile {
            get {
                return ResourceManager.GetString("MoveFile", resourceCulture);
            }
        }
        
        internal static string MoveResource {
            get {
                return ResourceManager.GetString("MoveResource", resourceCulture);
            }
        }
        
        internal static string MoveResourceDetail {
            get {
                return ResourceManager.GetString("MoveResourceDetail", resourceCulture);
            }
        }
        
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        internal static string DeletingInvalidResources {
            get {
                return ResourceManager.GetString("DeletingInvalidResources", resourceCulture);
            }
        }
        
        internal static string PostParser_ParseAll_TaskName {
            get {
                return ResourceManager.GetString("PostParser_ParseAll_TaskName", resourceCulture);
            }
        }
        
        internal static string SyncMediaLibrary {
            get {
                return ResourceManager.GetString("SyncMediaLibrary", resourceCulture);
            }
        }
        
        internal static string BTask_CanNotReplaceAnActiveTask {
            get {
                return ResourceManager.GetString("BTask_CanNotReplaceAnActiveTask", resourceCulture);
            }
        }
        
        internal static string SyncMediaLibrary_TaskProcess_DiscoverResources {
            get {
                return ResourceManager.GetString("SyncMediaLibrary_TaskProcess_DiscoverResources", resourceCulture);
            }
        }
        
        internal static string SyncMediaLibrary_TaskProcess_CleanupResources {
            get {
                return ResourceManager.GetString("SyncMediaLibrary_TaskProcess_CleanupResources", resourceCulture);
            }
        }
        
        internal static string SyncMediaLibrary_TaskProcess_AddResources {
            get {
                return ResourceManager.GetString("SyncMediaLibrary_TaskProcess_AddResources", resourceCulture);
            }
        }
        
        internal static string SyncMediaLibrary_TaskProcess_UpdateResources {
            get {
                return ResourceManager.GetString("SyncMediaLibrary_TaskProcess_UpdateResources", resourceCulture);
            }
        }
        
        internal static string SyncMediaLibrary_TaskProcess_AlmostComplete {
            get {
                return ResourceManager.GetString("SyncMediaLibrary_TaskProcess_AlmostComplete", resourceCulture);
            }
        }
        
        internal static string MediaType_Image {
            get {
                return ResourceManager.GetString("MediaType_Image", resourceCulture);
            }
        }
        
        internal static string MediaType_Audio {
            get {
                return ResourceManager.GetString("MediaType_Audio", resourceCulture);
            }
        }
        
        internal static string MediaType_Video {
            get {
                return ResourceManager.GetString("MediaType_Video", resourceCulture);
            }
        }
        
        internal static string MediaType_Text {
            get {
                return ResourceManager.GetString("MediaType_Text", resourceCulture);
            }
        }
        
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Enhancer_CircularDependencyDetected {
            get {
                return ResourceManager.GetString("Enhancer_CircularDependencyDetected", resourceCulture);
            }
        }
    }
}
