//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.Modules.Enhancer.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnhancerResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnhancerResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bakabase.Modules.Enhancer.Resources.EnhancerResource", typeof(EnhancerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Enhancer_Bakabase_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Language_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Language_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Language_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Language_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Name_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Name_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Name_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Originals_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Originals_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Publisher_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Publisher_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Publisher_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Publisher_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_ReleaseDt_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_ReleaseDt_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_ReleaseDt_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_ReleaseDt_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_VolumeName_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeName_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_VolumeName_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeName_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_VolumeTitle_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeTitle_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_VolumeTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_VolumeTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Name_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Cover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Tags_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Rating_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Introduction_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Description {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Name_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Tags_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Introduction_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Rating_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_OtherPropertiesInLeftPanel_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_OtherPropertiesInLeftPanel_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Cover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Originals_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Originals_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bakabase_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Bakabase_Target_Cover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Bangumi_Target_Rating_Description {
            get {
                return ResourceManager.GetString("Enhancer_Bangumi_Target_Rating_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_DLsite_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_DLsite_Target_Name_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Name_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_DLsite_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Cover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_DLsite_Target_PropertiesOnTheRightSideOfCover_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_PropertiesOnTheRightSideOfCover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_DLsite_Target_Introduction_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Introduction_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_DLsite_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_DLsite_Target_Rating_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Regex_Name {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Regex_Target_CaptureGroups_Name {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Target_CaptureGroups_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Regex_Description {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Regex_Target_CaptureGroups_Description {
            get {
                return ResourceManager.GetString("Enhancer_Regex_Target_CaptureGroups_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Description {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Title_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Title_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_OriginalTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_OriginalTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_SortTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_SortTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_ShowTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_ShowTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Outline_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Outline_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Plot_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Plot_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Tagline_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Tagline_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Runtime_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Runtime_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Mpaa_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Mpaa_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_PlayCount_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_PlayCount_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_LastPlayed_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_LastPlayed_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Id_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Id_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Genres_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Genres_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Countries_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Countries_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Tags_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Director_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Director_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Premiered_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Premiered_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Year_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Year_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Status_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Status_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Studio_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Studio_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Trailer_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Trailer_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Season_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Season_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Episode_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Episode_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Genre_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Genre_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_UserRating_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_UserRating_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Thumbs_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Thumbs_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_FanartThumbs_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_FanartThumbs_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Actors_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Actors_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Artist_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Artist_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Album_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Album_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_MusicVideo_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_MusicVideo_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Episodes_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Episodes_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Directors_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Directors_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Track_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Track_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Style_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Style_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Mood_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Mood_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Themes_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Themes_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Compilation_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Compilation_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_BoxSet_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_BoxSet_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Review_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Review_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Type_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Type_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_ReleaseStatus_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_ReleaseStatus_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_ReleaseDate_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_ReleaseDate_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_OriginalReleaseDate_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_OriginalReleaseDate_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Label_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Label_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Duration_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Duration_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Path_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Path_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Votes_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Votes_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_ReleaseType_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_ReleaseType_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Rating_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_SortName_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_SortName_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Gender_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Gender_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Disambiguation_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Disambiguation_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Styles_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Styles_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Moods_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Moods_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_YearsActive_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_YearsActive_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Born_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Born_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Formed_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Formed_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Biography_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Biography_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Died_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Died_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Disbanded_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Disbanded_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_AlbumArtistCredits_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_AlbumArtistCredits_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_VideoAssetTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_VideoAssetTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_VideoAssetId_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_VideoAssetId_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_VideoAssetType_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_VideoAssetType_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_HasVideoVersions_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_HasVideoVersions_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_HasVideoExtras_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_HasVideoExtras_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_IsDefaultVideoVersion_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_IsDefaultVideoVersion_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Credits_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Credits_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_DisplaySeason_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_DisplaySeason_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_DisplayEpisode_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_DisplayEpisode_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Code_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Code_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Aired_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Aired_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_DateAdded_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_DateAdded_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Top250_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Top250_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_UniqueIds_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_UniqueIds_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_NamedSeasons_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_NamedSeasons_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Set_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Set_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Resume_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Resume_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Kodi_Target_Ratings_Name {
            get {
                return ResourceManager.GetString("Enhancer_Kodi_Target_Ratings_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Target_Options_PropertyIdIsNullButPropertyTypeIsNot {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyIdIsNullButPropertyTypeIsNot", resourceCulture);
            }
        }
        
        public static string Enhancer_Target_Options_PropertyTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyTypeIsNotSupported", resourceCulture);
            }
        }
        
        public static string Enhancer_Target_Options_PropertyTypeIsNullButPropertyIdIsNot {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyTypeIsNullButPropertyIdIsNot", resourceCulture);
            }
        }
        
        public static string Enhancer_Target_Options_PropertyIdIsNotFoundInReservedResourceProperties {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyIdIsNotFoundInReservedResourceProperties", resourceCulture);
            }
        }
        
        public static string Enhancer_Target_Options_PropertyIdIsNotFoundInCustomResourceProperties {
            get {
                return ResourceManager.GetString("Enhancer_Target_Options_PropertyIdIsNotFoundInCustomResourceProperties", resourceCulture);
            }
        }
        
        public static string Enhancer_DeletingEnhancementRecords {
            get {
                return ResourceManager.GetString("Enhancer_DeletingEnhancementRecords", resourceCulture);
            }
        }
        
        public static string Enhancer_ReApplyingEnhancements {
            get {
                return ResourceManager.GetString("Enhancer_ReApplyingEnhancements", resourceCulture);
            }
        }
        
        public static string Enhancer_ExHentai_Target_Rating_Description {
            get {
                return ResourceManager.GetString("Enhancer_ExHentai_Target_Rating_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Description {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Title_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Title_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_OriginalTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_OriginalTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Overview_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Overview_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Rating_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Rating_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_VoteCount_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_VoteCount_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_ReleaseDate_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_ReleaseDate_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Runtime_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Runtime_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Genres_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Genres_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_ProductionCountries_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_ProductionCountries_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_SpokenLanguages_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_SpokenLanguages_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Status_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Status_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Tagline_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Tagline_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Budget_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Budget_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Revenue_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Revenue_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Cover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Tmdb_Target_Backdrop_Name {
            get {
                return ResourceManager.GetString("Enhancer_Tmdb_Target_Backdrop_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Description {
            get {
                return ResourceManager.GetString("Enhancer_Av_Description", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Number_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Number_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Title_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Title_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_OriginalTitle_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_OriginalTitle_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Actor_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Actor_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Tags_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Tags_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Release_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Release_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Year_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Year_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Studio_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Studio_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Publisher_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Publisher_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Series_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Series_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Runtime_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Runtime_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Director_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Director_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Source_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Source_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Cover_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Cover_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Poster_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Poster_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Website_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Website_Name", resourceCulture);
            }
        }
        
        public static string Enhancer_Av_Target_Mosaic_Name {
            get {
                return ResourceManager.GetString("Enhancer_Av_Target_Mosaic_Name", resourceCulture);
            }
        }
        
        public static string Enhance {
            get {
                return ResourceManager.GetString("Enhance", resourceCulture);
            }
        }
        
        public static string Enhancer_KeywordPropertyIsEmpty {
            get {
                return ResourceManager.GetString("Enhancer_KeywordPropertyIsEmpty", resourceCulture);
            }
        }
        
        public static string Enhancer_UsePropertyAsKeyword {
            get {
                return ResourceManager.GetString("Enhancer_UsePropertyAsKeyword", resourceCulture);
            }
        }
        
        public static string Enhancer_UseFilenameAsKeyword {
            get {
                return ResourceManager.GetString("Enhancer_UseFilenameAsKeyword", resourceCulture);
            }
        }
        
        public static string Enhancer_KeywordPretreatStatus {
            get {
                return ResourceManager.GetString("Enhancer_KeywordPretreatStatus", resourceCulture);
            }
        }
        
        public static string Enhancer_KeywordAfterPretreatment {
            get {
                return ResourceManager.GetString("Enhancer_KeywordAfterPretreatment", resourceCulture);
            }
        }
    }
}
