//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakabase.Modules.Comparison.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComparisonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComparisonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bakabase.Modules.Comparison.Resources.ComparisonResource", typeof(ComparisonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute resource comparison plan.
        /// </summary>
        public static string BTask_Description_Comparison {
            get {
                return ResourceManager.GetString("BTask_Description_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Task.
        /// </summary>
        public static string BTask_Name_Comparison {
            get {
                return ResourceManager.GetString("BTask_Name_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Map.
        /// </summary>
        public static string ComparisonMode_ExtensionMap {
            get {
                return ResourceManager.GetString("ComparisonMode_ExtensionMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Tolerance.
        /// </summary>
        public static string ComparisonMode_FixedTolerance {
            get {
                return ResourceManager.GetString("ComparisonMode_FixedTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Text.
        /// </summary>
        public static string ComparisonMode_NormalizedText {
            get {
                return ResourceManager.GetString("ComparisonMode_NormalizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Extract Number.
        /// </summary>
        public static string ComparisonMode_RegexExtractNumber {
            get {
                return ResourceManager.GetString("ComparisonMode_RegexExtractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Tolerance.
        /// </summary>
        public static string ComparisonMode_RelativeTolerance {
            get {
                return ResourceManager.GetString("ComparisonMode_RelativeTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Day.
        /// </summary>
        public static string ComparisonMode_SameDay {
            get {
                return ResourceManager.GetString("ComparisonMode_SameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Intersection.
        /// </summary>
        public static string ComparisonMode_SetIntersection {
            get {
                return ResourceManager.GetString("ComparisonMode_SetIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Equal.
        /// </summary>
        public static string ComparisonMode_StrictEqual {
            get {
                return ResourceManager.GetString("ComparisonMode_StrictEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset.
        /// </summary>
        public static string ComparisonMode_Subset {
            get {
                return ResourceManager.GetString("ComparisonMode_Subset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Similarity.
        /// </summary>
        public static string ComparisonMode_TextSimilarity {
            get {
                return ResourceManager.GetString("ComparisonMode_TextSimilarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Window.
        /// </summary>
        public static string ComparisonMode_TimeWindow {
            get {
                return ResourceManager.GetString("ComparisonMode_TimeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string NullValueBehavior_Fail {
            get {
                return ResourceManager.GetString("NullValueBehavior_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string NullValueBehavior_Pass {
            get {
                return ResourceManager.GetString("NullValueBehavior_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string NullValueBehavior_Skip {
            get {
                return ResourceManager.GetString("NullValueBehavior_Skip", resourceCulture);
            }
        }
    }
}
