name: Debug actions

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # ✅ pull code into workspace
      
      - name: Debug release context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"
      - name: Get version from nbgv & update manifest
        run: |
          VERSION="1.9.2-beta.25"
          echo "Using version from nbgv: $VERSION"
          jq --arg v "$VERSION" '.["."]=$v' .release-please-manifest.json > tmp && mv tmp .release-please-manifest.json
      - name: Debug manifest
        run: |
          echo "Manifest:"
          cat .release-please-manifest.json
      - name: Run release-please (manifest)
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}