name: Debug actions

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  debug-git-cliff:
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4   # ✅ pull code into workspace
        with:
          fetch-depth: 0
      
      - name: Debug release context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: 1.9.2-beta.1..1.9.2-beta.37 -vv --tag 1.9.2-beta.37
        env:
          CLIFF_ARCH: x86_64
          GITHUB_REPO: ${{ github.repository }}

      - name: Show changelog
        run: |
          echo "Generated changelog:"
          echo "${{ steps.git-cliff.outputs.content }}"