name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
          
      - name: Clone other repos
        run: |
          git clone https://github.com/anobaka/Bakabase.Infrastructures.git
          git clone https://github.com/anobaka/LazyMortal.git
          
      - name: Clone private Bakabase.CI
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BAKABASE_CI_TOKEN }}
          repository: anobaka/Bakabase.CI
          path: Bakabase.CI
          
      - name: List current directory
        run: |
          ls -l
          
      - name: Run build.sh in main repo
        run: |
          cd Bakabase.CI
          bash docker/build.sh -t latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag and push Docker image
        run: |
          docker tag bakabase:latest ${{ secrets.DOCKERHUB_USERNAME }}/bakabase:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bakabase:latest
