name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
          
      - name: Clone other repos to parent directory
        run: |
          git clone https://github.com/anobaka/Bakabase.Infrastructures.git
          git clone https://github.com/anobaka/LazyMortal.git
          
      - name: Clone private Bakabase.CI
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BAKABASE_CI_TOKEN }}
          repository: anobaka/Bakabase.CI
          
      - name: List current directory
        run: |
          ls -l
